language: objective-c
before_install:
  - gem install cocoapods -v '1.2.0'
cache:
  - cocoapods
notifications:
  email: jianghaoyuan@e-eduspace.com
script: set -o pipefail && xcodebuild -workspace 'RxAlamofire.xcworkspace' -scheme 'RxAlamofireTests' -configuration 'Debug' -sdk iphonesimulator -destination platform='iOS Simulator',OS='10.0',name='iPhone 7' build test  | xcpretty -c --test
