language: objective-c
before_install:
  - gem install cocoapods -v '1.2.0'
cache:
  - cocoapods
notifications:
  email: jianghaoyuan@e-eduspace.com
xcode_sdk: iphonesimulator10.2
script: set -o pipefail && xcodebuild -workspace 'RxAlamofire.xcworkspace' -scheme 'RxAlamofire-iOS' -configuration 'Debug' build test  | xcpretty -c --test
