osx_image: xcode8.2
language: objective-c
cache:
  - cocoapods
before_install:
xcode-workspace: RxAlamofire.xcworkspace
xcode-scheme: RxAlamofire-iOS
xcode_sdk: iphonesimulator10.2
  - gem install cocoapods -v '1.2.0'
script: xcodebuild -workspace 'RxAlamofire.xcworkspace' -scheme 'RxAlamofire-iOS' -configuration 'Debug' build test  | xcpretty -c --test